### ISSUE TITLE
Append tags to existing ones?

### ISSUE THREAD

**Issue by rosgr100** [Al00X/MB_QuickTagger#1]
Hi, firstly your plugin is really useful and thank you for it.

I would kindly want to ask you if you intend to update it and add an append/add new values to existing one instead of replacing.

Thank you

**Comment by rosgr100** [comment]
Nevermind, i did it.

Also added the ability to remove a value if you choose it again.

Thank you for this amazing plugin.

**Comment by Al00X** [comment]
@rosgr100 feel free to create a Pull Request!
Glad you found this plugin useful <3
